---
- name: INCLUDE SHOW COMMANDS VARIABLES FILE
  include_vars: vars/main.yml

- name: Checking Pre-change ACL
  cisco.ios.ios_command:
    commands:
    - show ip access-list 1
  register: pre_change_acl
 
- name: Logging Step 1
  ansible.builtin.debug:
    msg: " Old ACL Resgistred "
 
- name: Copying File
  ansible.builtin.copy:
    content: "{{ pre_change_acl.stdout[0] }}" 
    dest: "./acl_and_syslog_update/acl_output/{{ inventory_hostname }}_pre_acl.txt"

 
- name: Configuring new acl
  cisco.ios.ios_config:
    lines: "{{ command_list }}"       
    parents: ip access-list standard 1
    before: no ip access-list standard 1
    match: exact
    
- name: Logging Step 2
  ansible.builtin.debug:
    msg: "New ACL Pushed"
    
    
- name: Checking pos-change ACL
  cisco.ios.ios_command:
    commands:
    - show ip access-list 1
  register: pos_change_acl

- name: Logging Step 3
  ansible.builtin.debug:
    msg: "New ACL Resgitered"
    
    
- name: Copying File
  ansible.builtin.copy:
    content: "{{ pos_change_acl.stdout[0] }}" 
    dest: "./acl_and_syslog_update/acl_output/{{ inventory_hostname }}_pos_acl.txt"
