---
all:
  children:
    # ansible_controller:
    #   hosts:
    #     localhost:
    #       ansible_host: 127.0.0.1
    #   vars:
    #     connection: local
    ny4_dc:
      children:
        nx-os:
          hosts:
            core-01:
              ansible_host: 192.168.1.143
            core-21:
              ansible_host: 192.168.1.147
            leaf0-1:
              ansible_host: 192.168.1.148
        arista_os:
          hosts:
            edge-01:
              ansible_host: 192.168.1.125
            cedge-02:
              ansible_host: 192.168.1.147
          vars:
            ansible_network_os: arista.eos.eos  
            ansible_become_method: enable
            ansible_user: admin
            ansible_ssh_pass: cisco123
     
