devices:
  io-xe:
      csr:
        host: '192.168.1.120'
        device_type: 'cisco_ios'
  nx-os:
      cedge-01:
        host: '192.168.1.120'
        device_type: 'cisco_nxos'
      cedge-02:
        host: '192.168.1.120'
        device_type: 'cisco_nxos'
  eos:
      sleaf-01:
        host: '192.168.1.125'
        device_type: 'arista_eos'
      sleaf-02:
        host: '192.168.1.109'
        device_type: 'arista_eos'


