---

- name: Cat9300 L3 Temaplate Creation
  hosts: "127.0.0.1"
  gather_facts: false
  connection: local
  vars_prompt:
    - name: "hostname"
      prompt: "Enter Cat9300's Hostname?"
      private: no

  vars_files: 
    - /root/network_automation/iosxe/roles/create/vars/{{ hostname }}_vars.yml

  tasks:
    - name: Creating Tamplate
      ansible.builtin.template:
        src: "/root/network_automation/iosxe/roles/create/templates/cat9300_l3_temp.j2"
        dest: "/root/network_automation/iosxe/complete/{{ hostname }}.txt"