---
- name: INCLUDE SHOW COMMANDS VARIABLES FILE
  include_vars: vars/new_syslogs_vars.yml

- name: Checking Pre-change Logging Servers
  cisco.ios.ios_command:
    commands:
     - show runn | in logging host
  register: pre_change_logg
     
- name: Log server Step 1 
  ansible.builtin.debug:
    msg: "Old logging servers Registred"
 
- name: Copying File
  ansible.builtin.copy:
    content: "{{ pre_change_logg.stdout[0] }}" 
    dest: "./acl_and_syslog_update/syslogs_output/{{ inventory_hostname }}_pre_logg.txt"


- name: Configuring new logging Servers
  cisco.ios.ios_config:
    lines: "{{ command_list }}"

    
- name: Log server Step 2
  ansible.builtin.debug:
    msg: "New logging servers Configured"

- name: Checking Pos-change Logging Servers
  cisco.ios.ios_command:
    commands:
    - show runn | in logging host
  register: pos_change_logg 
    
    
- name: Copying File
  ansible.builtin.copy:
    content: "{{ pos_change_logg.stdout[0] }}" 
    dest: "./acl_and_syslog_update/syslogs_output/{{ inventory_hostname }}_pos_logg.txt"