---
- name: checking IOS Code
  hosts: all
  gather_facts: false
  connection: network_cli
  
  tasks:
    - name: run show version and check to see if output contains IOS
      cisco.ios.ios_facts:
        gather_subset: all

    - name: Saving output
      debug:
        msg:  "{{ inventory_hostname }} is {{ ansible_net_model }}" 